"""create new table 'Review' and relationships for tables 'Product' and 'User'

Revision ID: c93b33670450
Revises: 9c9939b033ea
Create Date: 2026-03-09 22:06:58.483507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93b33670450'
down_revision: Union[str, Sequence[str], None] = '9c9939b033ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
